name: inai_flutter_sdk
description: Inai Flutter SDK
version: 0.1.5
homepage: "https://github.com/inaitech/inai-flutter-sdk"
documentation: "https://docs.inai.io/docs/flutter"
platforms:
  android:
  ios:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  webview_flutter: ^3.0.0
  http: ^1.1.0
  pay: ^1.1.0
  yaml: ^3.1.1
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
